---

- name: Install WireGuard
  homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - wireguard-tools
  tags:
    - wg-install
    - skip_ansible_lint
  become: yes
  become_method: su
  become_user: "{{ wireguard_macos_homebrew_user }}"


- name: Create WireGuard configuration directory
  file:
    dest: "{{ wireguard_macos_remote_directory }}"
    state: directory
    mode: 0700
    owner: "{{ wireguard_macos_homebrew_user }}"
  tags:
   - wg-config
