---
#- name: Gather instance facts
#  setup:

- include_tasks: "install.yml"
  when: wireguard_install

- include_tasks: "configure/{{ ansible_system|lower }}.yml"
  with_items: "{{ wireguard_networks }}"
  tags:
    - configure
